version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis_network
    restart: always

networks:
  redis_network:
    driver: bridge
